### PR TITLE
fixed the segfault problem by cleaning the url, closes #104

### LINKED ISSUE #104: Links shortening segmentation fault
For some reasons, bitbot sometimes prints a segmentation fault message instead of a shortened url.

### PR DESCRIPTION
**Pull request by m-242**

### CODE REVIEW

File: bitbot/links.go [hunk 1]
```diff
@@ -20,16 +22,21 @@ var URLReaderTrigger = NamedTrigger{
...
+			} else {
+				irc.Reply(m, title)
 			}
 		}
 		return true
 	},
 }
 
-func shortenURL(uri string) string {
+func shortenURL(uri string, title string) string {
```
Comment (bbriggs) [inline bitbot/links.go]: Let's leave this function signature the same and extract the URI + concatenate the message elsewhere. The shortenURL function should work as advertised and only shorten URLs, not also extract and concatenate.
